repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 100MB
        entry: .pre-commit-hooks/check-large-files.sh
        language: system
        args: ['--maxkb=102400']  # 100MB = 102400KB
